spring:
  application:
    name: customers

server:
  port: 9000

integration:
  stores:
    uri: http://localhost:8081

# For demo only allow more hystrix connections
hystrix:
  stream:
    maxConcurrentConnections: 20

logging:
  level:
    com.netflix.discovery: WARN